### ISSUE TITLE
Compatibility with Jekyll 3.0

### ISSUE THREAD

**Issue by dboulet** [ivantsepp/jekyll-autolink_email#3]
Would it be possible to make a new release of this plugin, which is compatible with Jekyll 3.0?

**Comment by jimcavoli** [comment]
See my pull request on #4 for those changes. Until/if the PR gets merged back and a new version of the gem is released for Jekyll 3 compatibility, you can track the master branch on my repo in your Gemfile like so: `gem 'jekyll-autolink_email', git: 'https://github.com/jimcavoli/jekyll-autolink_email'`

**Comment by ivantsepp** [comment]
I'm sorry for the LONG delay. New version is out https://rubygems.org/gems/jekyll-autolink_email/versions/0.1.0
